service: docker-as-lambda

licenseKey: ${ssm:/aws/reference/secretsmanager/serverless-framework-access-key}

provider:
  deploymentBucket:
    name: com.reference-architecture.deploys
  environment:
    POWERTOOLS_LOGGER_SAMPLE_RATE: 1
  ecr:
    images:
      app_image:
        path: ./
  logRetentionInDays: 7
  name: aws

functions:
  hello:
    image:
      name: app_image
    events:
      - httpApi:
          method: get
          path: /hello

plugins:
  - serverless-deployment-bucket

package:
  individually: true
